
### Oauth2.0注册
POST  {{oauth-api}}/api/v1/oauth2.0/register
Content-Type: application/json

{
  "clientId": "{{clientId}}",
  "versionId": "{{versionId}}",
  "nickName": "微信公众号:储凡",
  "account": "142vip",
  "password": "123456"
}


### 获取授权码，开始OAuth2.0协议
POST  {{oauth-api}}/api/v1/oauth2.0/authorize?clientId={{clientId}}&versionId={{versionId}}&returnUri={{returnUri}}&
    scope=login&responseType=code&redirectType=no_auto&state={{$randomInt}}
Content-Type: application/json

{
  "account": "142vip",
  "password": "123456"
}


### 访问令牌accessToken
POST {{oauth-api}}/api/v1/oauth2.0/token
Content-Type: application/json

{
  "clientId": "{{clientId}}",
  "versionId": "{{versionId}}",
  "returnUri": "{{returnUri}}",
  "state": "{{$random.integer()}}",
  "grantType": "authorization_code",
  "authorizationCode": "{{authorizationCode}}",
  "clientSecret": "{{clientSecret}}"
}


### 授权，加上Bearer 校验accessToken 获取jwt信息
POST {{oauth-api}}/api/v1/oauth2.0/authenticate
Content-Type: application/json
Authorization: {{accessToken}}


### 刷新访问令牌
POST {{oauth-api}}/api/v1/oauth2.0/refresh
Content-Type: application/json
Authorization: {{accessToken}}

### 修改用户密码
POST {{oauth-api}}/api/v1/oauth2.0/password


### 客户端用户注册 带上版本
POST {{oauth-api}}/api/v1/oauth2.0/register



### 用户登录
POST {{oauth-api}}/api/v1/login
Content-Type: application/json

{
  "account": "142vip",
  "password": "123456",
  "userType": 2
}


### 用户注册
POST {{oauth-api}}/api/v1/register
Content-Type: application/json

{
  "account": "142vip",
  "password": "123456",
  "userType": 2,
  "nickName": "微信公众号：储凡"
}

### 用户退出
POST {{oauth-api}}/api/v1/logout
Authorization: {{accessToken}}


### 获取当前登录用户信息
POST {{oauth-api}}/api/v1/loginInfo
Authorization: {{accessToken}}


### 获取Oauth客户端基础信息
POST {{oauth-api}}/api/v1/client/baseInfo
Authorization: {{accessToken}}


### 生成验证码
GET {{oauth-api}}/api/v1/randomVerifyCode?verifyKey=1231232312&type=simple



### 新增客户端
POST {{oauth-api}}/api/v1/client
Authorization: {{accessToken}}
Content-Type: application/json

{
  "name": "Oauth2.0授权客户端-测试",
  "indexAddress": "http://127.0.0.1:9100",
  "description": "用于授权测试"
}

### 查看客户端接入信息
POST {{oauth-api}}/api/v1/client/list
Content-Type: application/json
Authorization: {{accessToken}}


### 更新客户端信息
POST {{oauth-api}}/api/v1/client/info
Content-Type: application/json
Authorization: {{accessToken}}

{
  "clientId": "{{clientId}}",
  "description": "接口调用测试修改",
  "state": 0
}


### 创建客户端应用信息
POST {{oauth-api}}/api/v1/app
Content-Type: application/json
Authorization: {{accessToken}}

{
  "clientId": "{{clientId}}",
  "name": "Web端",
  "version": "0.0.1",
  "description": "接口调用测试修改"
}

### 查询客户端应用列表

POST {{oauth-api}}/api/v1/app/list
Content-Type: application/json
Authorization: {{accessToken}}

{
  "clientId": "{{clientId}}"
}


