#!/bin/bash
##
## 依赖安装脚本
## 使用:
##   ./scripts/ci
##

# 安装pnpm版本
COREPACK_NPM_REGISTRY=https://registry.npmmirror.com corepack enable pnpm

## 获取所有参数
echo "运行命令: pnpm i --frozen-lockfile --registry https://registry.npmmirror.com $*"

# 安装项目依赖 -w -F @142vip/fairy-cli
pnpm i --frozen-lockfile --registry https://registry.npmmirror.com "$@"
